### PR TITLE
207-Python initial

### PR DESCRIPTION
**Pull request by ErdemT09**
[Original issue.](https://github.com/spiralgo/algorithms/blob/master/src/main/java/algorithms/curated170/easy/ClosestBinarySearchTreeValue.java)

Problem here: I couldn't manage importing the Tree Node data structure to the algorithm's code. I have looked up for solutions online but somethings seem to be not working with this.

### CODE REVIEW

**Comment by altayhunoglu** [comment]
Could we try to add an "environment variable" path like this: PYTHONPATH?
It should be the path of the folder containing "algorithm-pyton"

image

Then, we can try like that:
```

import math
from data_structures.tree_node import TreeNode
class Solution:
    current_best = -1

    def closestValue(self, root, target):
        if root == None:
            return self.current_best
        current_val = root.val
        if self.current_best == -1:
            self.current_best = root.val
        self.current_best = current_val if abs(
            current_val-target) < abs(self.current_best-target) else self.current_best
        if target < current_val:
            self.closestValue(root.left, target)
        elif target > current_val:
            self.closestValue(root.right, target)

        return self.current_best


if __name__ == "__main__":
    s = Solution()
    root = TreeNode(8)  
root.left = TreeNode(5)  
root.right = TreeNode(14) 
root.left.left = TreeNode(4)  
root.left.right = TreeNode(6) 
root.left.right.left = TreeNode(8)  
root.left.right.right = TreeNode(7)  
root.right.right = TreeNode(24) 
root.right.right.left = TreeNode(22)  
    
result =  s.closestValue(root, 19)
print(result)
```

**Comment by altayhunoglu** [comment]
If you use a Unix/Linux/macOS version, then you can use the export command instead:
 
` export PYTHONPATH="${PYTHONPATH}:/my/other/path"
`

**Comment by ErdemT09** [comment]
Works.

**Comment by altayhunoglu** [comment]
> Works.

Happy to hear that.

**Review by altayhunoglu — APPROVED** [review]
It is okay, I think.

**Pull request merged**
